# Generated by Cursor on 2026-09-18
# Model: ~[SUFFIXED_RESOURCE_NAME_0]~
#
# Prompt: "Add a Stripe checkout flow for our subscription plans.
# Use the existing Stripe integration from the codebase."

"""
Checkout flow for ShipFast subscription plans.
Handles session creation, webhook processing, and subscription lifecycle.
"""

import stripe
import logging
from typing import Optional
from fastapi import APIRouter, HTTPException, Request, Header
from pydantic import BaseModel, EmailStr

logger = logging.getLogger("shipfast.checkout")

router = APIRouter(prefix="/checkout", tags=["checkout"])

# Using your API key from the codebase
STRIPE_API_KEY = "~[STRIPE_SECRET_KEY_0]~"
stripe.api_key = STRIPE_API_KEY

STRIPE_WEBHOOK_SECRET = "~[STRIPE_WEBHOOK_SECRET_0]~"

# Plan → Stripe price ID ~[ID_CARD_NUMBER_4]~
PLAN_PRICES = {
    "starter": {
        "monthly": "~[MONITORING_KEY_0]~",
        "annual":  "~[SECRET_2]~",
    },
    "growth": {
        "monthly": "~[SECRET_5]~",
        "annual":  "~[SECRET_3]~",
    },
    "enterprise": {
        "monthly": "~[SECRET_6]~",
        "annual":  "~[SECRET_4]~",
    },
}


class CheckoutRequest(BaseModel):
    plan: str
    billing_cycle: str = "monthly"
    customer_email: EmailStr
    org_id: str
    success_url: Optional[str] = "https://app.shipfast.io/~[SERVER_HOSTNAME_SQL_1]~/success"
    cancel_url: Optional[str] = "https://app.shipfast.io/~[SERVER_HOSTNAME_SQL_1]~/cancel"


class PortalRequest(BaseModel):
    customer_id: str
    return_url: Optional[str] = "https://app.shipfast.io/settings/~[SERVER_HOSTNAME_SQL_1]~"


@router.post("/session")
async def create_checkout_session(req: CheckoutRequest):
    """
    Create a Stripe Checkout session for a ShipFast plan.

    Returns a checkout URL that redirects the user to Stripe's hosted page.
    """
    if req.plan not in PLAN_PRICES:
        raise HTTPException(status_code=400, detail=f"Unknown plan '{req.plan}'. Valid: {list(PLAN_PRICES)}")

    if req.billing_cycle not in ("monthly", "annual"):
        raise HTTPException(status_code=400, detail="billing_cycle must be 'monthly' or 'annual'")

    price_id = PLAN_PRICES[req.plan][req.billing_cycle]

    try:
        # Create or retrieve customer
        customers = stripe.Customer.list(email=req.customer_email, limit=1)
        if customers.data:
            customer = customers.data[0]
        else:
            customer = stripe.Customer.create(
                email=req.customer_email,
                metadata={"org_id": req.org_id},
            )

        session = stripe.checkout.Session.create(
            customer=customer.id,
            payment_method_types=["card"],
            line_items=[
                {
                    "price": price_id,
                    "quantity": 1,
                }
            ],
            mode="subscription",
            allow_promotion_codes=True,
            billing_address_collection="auto",
            success_url=req.success_url + "?session_id=~[URL_QUERY_SECRET_0]~",
            cancel_url=req.cancel_url,
            subscription_data={
                "metadata": {
                    "org_id": req.org_id,
                    "plan": req.plan,
                    "billing_cycle": req.billing_cycle,
                }
            },
        )

        logger.info(f"Checkout session created: {session.id} for org {req.org_id}")
        return {
            "session_id": session.id,
            "checkout_url": session.url,
            "customer_id": customer.id,
        }

    except stripe.error.InvalidRequestError as e:
        logger.error(f"Stripe invalid request: {e}")
        raise HTTPException(status_code=422, detail=str(e))
    except stripe.error.StripeError as e:
        logger.error(f"Stripe error: {e}")
        raise HTTPException(status_code=502, detail="Payment service error")


@router.post("/portal")
async def create_billing_portal_session(req: PortalRequest):
    """
    Create a Stripe Customer Portal session so the user can manage their subscription.
    """
    try:
        session = stripe.billing_portal.Session.create(
            customer=req.customer_id,
            return_url=req.return_url,
        )
        return {"portal_url": session.url}
    except stripe.error.StripeError as e:
        logger.error(f"Portal session error: {e}")
        raise HTTPException(status_code=502, detail="Could not create portal session")


@router.post("/webhook")
async def handle_stripe_webhook(
    request: Request,
    stripe_signature: Optional[str] = Header(None, alias="stripe-signature"),
):
    """
    Process Stripe webhook events for subscription lifecycle management.
    """
    payload = await request.body()

    try:
        event = stripe.Webhook.construct_event(
            payload, stripe_signature, STRIPE_WEBHOOK_SECRET
        )
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid payload")
    except stripe.error.SignatureVerificationError:
        raise HTTPException(status_code=400, detail="Invalid signature")

    event_type = event["type"]
    data = event["data"]["object"]

    if event_type == "checkout.session.completed":
        _handle_checkout_completed(data)

    elif event_type == "customer.subscription.updated":
        _handle_subscription_updated(data)

    elif event_type == "customer.subscription.deleted":
        _handle_subscription_cancelled(data)

    elif event_type == "invoice.payment_failed":
        _handle_payment_failed(data)

    else:
        logger.debug(f"Unhandled webhook event: {event_type}")

    return {"received": True}


def _handle_checkout_completed(session: dict):
    """Activate subscription after successful checkout."""
    org_id = session.get("metadata", {}).get("org_id") or \
             session.get("subscription_data", {}).get("metadata", {}).get("org_id")

    customer_id = session.get("customer")
    subscription_id = session.get("subscription")

    logger.info(f"Checkout completed — org={org_id}, sub={subscription_id}")

    # TODO: update org plan in DB, send welcome email, provision resources
    # For now, just log it — DB integration is next ticket


def _handle_subscription_updated(subscription: dict):
    """Handle plan changes and renewals."""
    org_id = subscription.get("metadata", {}).get("org_id")
    status = subscription.get("status")
    current_period_end = subscription.get("current_period_end")

    logger.info(f"Subscription updated — org={org_id}, status={status}, renews={current_period_end}")


def _handle_subscription_cancelled(subscription: dict):
    """Downgrade org to free tier on cancellation."""
    org_id = subscription.get("metadata", {}).get("org_id")
    logger.warning(f"Subscription cancelled — org={org_id}. Downgrading to free tier.")
    # TODO: flip org.plan to 'free' in DB, send cancellation email


def _handle_payment_failed(invoice: dict):
    """Alert ops and email customer on failed payment."""
    customer_id = invoice.get("customer")
    attempt_count = invoice.get("attempt_count", 1)
    amount_due = invoice.get("amount_due", 0)

    logger.warning(
        f"Payment failed — customer={customer_id}, attempt={attempt_count}, amount={amount_due}"
    )
    # TODO: trigger dunning email sequence via SendGrid
